package com.subway.ssm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SubwayInfoExample {
    /**
     * subway_info
     */
    protected String orderByClause;

    /**
     * subway_info
     */
    protected boolean distinct;

    /**
     * subway_info
     */
    protected List<Criteria> oredCriteria;

    /**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database table subway_info
    *
    * @mbggenerated Tue Mar 13 23:29:20 CST 2021
    */
    private List<String> sumCols;

    /**
     * subway_info
     */
    protected Integer offset;

    /**
     * subway_info
     */
    protected Integer rows;

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public SubwayInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.sumCols = null;
        rows = null;
        offset = null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table subway_info
    *
    * @mbggenerated Tue Mar 13 23:29:20 CST 2021
    */
    public List<String> getSumCols() {
        return this.sumCols;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table subway_info
    *
    * @mbggenerated Tue Mar 13 23:29:20 CST 2021
    */
    public void setSumCols(List<String> sumCols) {
        this.sumCols = sumCols;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public SubwayInfoExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public SubwayInfoExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     *
     * @mbg.generated 2021-03-23
     */
    public SubwayInfoExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * subway_info 2021-03-23
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubwayIdIsNull() {
            addCriterion("subway_id is null");
            return (Criteria) this;
        }

        public Criteria andSubwayIdIsNotNull() {
            addCriterion("subway_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayIdEqualTo(Long value) {
            addCriterion("subway_id =", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdNotEqualTo(Long value) {
            addCriterion("subway_id <>", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdGreaterThan(Long value) {
            addCriterion("subway_id >", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subway_id >=", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdLessThan(Long value) {
            addCriterion("subway_id <", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdLessThanOrEqualTo(Long value) {
            addCriterion("subway_id <=", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdIn(List<Long> values) {
            addCriterion("subway_id in", values, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdNotIn(List<Long> values) {
            addCriterion("subway_id not in", values, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdBetween(Long value1, Long value2) {
            addCriterion("subway_id between", value1, value2, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdNotBetween(Long value1, Long value2) {
            addCriterion("subway_id not between", value1, value2, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayNameIsNull() {
            addCriterion("subway_name is null");
            return (Criteria) this;
        }

        public Criteria andSubwayNameIsNotNull() {
            addCriterion("subway_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayNameEqualTo(String value) {
            addCriterion("subway_name =", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotEqualTo(String value) {
            addCriterion("subway_name <>", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameGreaterThan(String value) {
            addCriterion("subway_name >", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameGreaterThanOrEqualTo(String value) {
            addCriterion("subway_name >=", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameLessThan(String value) {
            addCriterion("subway_name <", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameLessThanOrEqualTo(String value) {
            addCriterion("subway_name <=", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameLike(String value) {
            addCriterion("subway_name like", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotLike(String value) {
            addCriterion("subway_name not like", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameIn(List<String> values) {
            addCriterion("subway_name in", values, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotIn(List<String> values) {
            addCriterion("subway_name not in", values, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameBetween(String value1, String value2) {
            addCriterion("subway_name between", value1, value2, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotBetween(String value1, String value2) {
            addCriterion("subway_name not between", value1, value2, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkIsNull() {
            addCriterion("subway_remark is null");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkIsNotNull() {
            addCriterion("subway_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkEqualTo(String value) {
            addCriterion("subway_remark =", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkNotEqualTo(String value) {
            addCriterion("subway_remark <>", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkGreaterThan(String value) {
            addCriterion("subway_remark >", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("subway_remark >=", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkLessThan(String value) {
            addCriterion("subway_remark <", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkLessThanOrEqualTo(String value) {
            addCriterion("subway_remark <=", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkLike(String value) {
            addCriterion("subway_remark like", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkNotLike(String value) {
            addCriterion("subway_remark not like", value, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkIn(List<String> values) {
            addCriterion("subway_remark in", values, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkNotIn(List<String> values) {
            addCriterion("subway_remark not in", values, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkBetween(String value1, String value2) {
            addCriterion("subway_remark between", value1, value2, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andSubwayRemarkNotBetween(String value1, String value2) {
            addCriterion("subway_remark not between", value1, value2, "subwayRemark");
            return (Criteria) this;
        }

        public Criteria andStartingTimeIsNull() {
            addCriterion("starting_time is null");
            return (Criteria) this;
        }

        public Criteria andStartingTimeIsNotNull() {
            addCriterion("starting_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartingTimeEqualTo(Date value) {
            addCriterion("starting_time =", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeNotEqualTo(Date value) {
            addCriterion("starting_time <>", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeGreaterThan(Date value) {
            addCriterion("starting_time >", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("starting_time >=", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeLessThan(Date value) {
            addCriterion("starting_time <", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeLessThanOrEqualTo(Date value) {
            addCriterion("starting_time <=", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeIn(List<Date> values) {
            addCriterion("starting_time in", values, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeNotIn(List<Date> values) {
            addCriterion("starting_time not in", values, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeBetween(Date value1, Date value2) {
            addCriterion("starting_time between", value1, value2, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeNotBetween(Date value1, Date value2) {
            addCriterion("starting_time not between", value1, value2, "startingTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }
    }

    /**
     * subway_info
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * subway_info 2021-03-23
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}