package com.subway.ssm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SubwayStationInfoExample {
    /**
     * subway_station_info
     */
    protected String orderByClause;

    /**
     * subway_station_info
     */
    protected boolean distinct;

    /**
     * subway_station_info
     */
    protected List<Criteria> oredCriteria;

    /**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database table subway_station_info
    *
    * @mbggenerated Wed May 19 00:17:37 CST 2021
    */
    private List<String> sumCols;

    /**
     * subway_station_info
     */
    protected Integer offset;

    /**
     * subway_station_info
     */
    protected Integer rows;

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public SubwayStationInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.sumCols = null;
        rows = null;
        offset = null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table subway_station_info
    *
    * @mbggenerated Wed May 19 00:17:37 CST 2021
    */
    public List<String> getSumCols() {
        return this.sumCols;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table subway_station_info
    *
    * @mbggenerated Wed May 19 00:17:37 CST 2021
    */
    public void setSumCols(List<String> sumCols) {
        this.sumCols = sumCols;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public SubwayStationInfoExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public SubwayStationInfoExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     *
     * @mbg.generated 2021-05-05
     */
    public SubwayStationInfoExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * subway_station_info 2021-05-05
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubwayStationIdIsNull() {
            addCriterion("subway_station_id is null");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdIsNotNull() {
            addCriterion("subway_station_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdEqualTo(Long value) {
            addCriterion("subway_station_id =", value, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdNotEqualTo(Long value) {
            addCriterion("subway_station_id <>", value, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdGreaterThan(Long value) {
            addCriterion("subway_station_id >", value, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subway_station_id >=", value, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdLessThan(Long value) {
            addCriterion("subway_station_id <", value, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdLessThanOrEqualTo(Long value) {
            addCriterion("subway_station_id <=", value, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdIn(List<Long> values) {
            addCriterion("subway_station_id in", values, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdNotIn(List<Long> values) {
            addCriterion("subway_station_id not in", values, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdBetween(Long value1, Long value2) {
            addCriterion("subway_station_id between", value1, value2, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationIdNotBetween(Long value1, Long value2) {
            addCriterion("subway_station_id not between", value1, value2, "subwayStationId");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameIsNull() {
            addCriterion("subway_station_name is null");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameIsNotNull() {
            addCriterion("subway_station_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameEqualTo(String value) {
            addCriterion("subway_station_name =", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameNotEqualTo(String value) {
            addCriterion("subway_station_name <>", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameGreaterThan(String value) {
            addCriterion("subway_station_name >", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameGreaterThanOrEqualTo(String value) {
            addCriterion("subway_station_name >=", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameLessThan(String value) {
            addCriterion("subway_station_name <", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameLessThanOrEqualTo(String value) {
            addCriterion("subway_station_name <=", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameLike(String value) {
            addCriterion("subway_station_name like", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameNotLike(String value) {
            addCriterion("subway_station_name not like", value, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameIn(List<String> values) {
            addCriterion("subway_station_name in", values, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameNotIn(List<String> values) {
            addCriterion("subway_station_name not in", values, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameBetween(String value1, String value2) {
            addCriterion("subway_station_name between", value1, value2, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationNameNotBetween(String value1, String value2) {
            addCriterion("subway_station_name not between", value1, value2, "subwayStationName");
            return (Criteria) this;
        }

        public Criteria andSubwayIdIsNull() {
            addCriterion("subway_id is null");
            return (Criteria) this;
        }

        public Criteria andSubwayIdIsNotNull() {
            addCriterion("subway_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayIdEqualTo(Long value) {
            addCriterion("subway_id =", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdNotEqualTo(Long value) {
            addCriterion("subway_id <>", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdGreaterThan(Long value) {
            addCriterion("subway_id >", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subway_id >=", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdLessThan(Long value) {
            addCriterion("subway_id <", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdLessThanOrEqualTo(Long value) {
            addCriterion("subway_id <=", value, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdIn(List<Long> values) {
            addCriterion("subway_id in", values, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdNotIn(List<Long> values) {
            addCriterion("subway_id not in", values, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdBetween(Long value1, Long value2) {
            addCriterion("subway_id between", value1, value2, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayIdNotBetween(Long value1, Long value2) {
            addCriterion("subway_id not between", value1, value2, "subwayId");
            return (Criteria) this;
        }

        public Criteria andSubwayNameIsNull() {
            addCriterion("subway_name is null");
            return (Criteria) this;
        }

        public Criteria andSubwayNameIsNotNull() {
            addCriterion("subway_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayNameEqualTo(String value) {
            addCriterion("subway_name =", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotEqualTo(String value) {
            addCriterion("subway_name <>", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameGreaterThan(String value) {
            addCriterion("subway_name >", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameGreaterThanOrEqualTo(String value) {
            addCriterion("subway_name >=", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameLessThan(String value) {
            addCriterion("subway_name <", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameLessThanOrEqualTo(String value) {
            addCriterion("subway_name <=", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameLike(String value) {
            addCriterion("subway_name like", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotLike(String value) {
            addCriterion("subway_name not like", value, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameIn(List<String> values) {
            addCriterion("subway_name in", values, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotIn(List<String> values) {
            addCriterion("subway_name not in", values, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameBetween(String value1, String value2) {
            addCriterion("subway_name between", value1, value2, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayNameNotBetween(String value1, String value2) {
            addCriterion("subway_name not between", value1, value2, "subwayName");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoIsNull() {
            addCriterion("subway_station_info is null");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoIsNotNull() {
            addCriterion("subway_station_info is not null");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoEqualTo(String value) {
            addCriterion("subway_station_info =", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoNotEqualTo(String value) {
            addCriterion("subway_station_info <>", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoGreaterThan(String value) {
            addCriterion("subway_station_info >", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoGreaterThanOrEqualTo(String value) {
            addCriterion("subway_station_info >=", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoLessThan(String value) {
            addCriterion("subway_station_info <", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoLessThanOrEqualTo(String value) {
            addCriterion("subway_station_info <=", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoLike(String value) {
            addCriterion("subway_station_info like", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoNotLike(String value) {
            addCriterion("subway_station_info not like", value, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoIn(List<String> values) {
            addCriterion("subway_station_info in", values, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoNotIn(List<String> values) {
            addCriterion("subway_station_info not in", values, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoBetween(String value1, String value2) {
            addCriterion("subway_station_info between", value1, value2, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andSubwayStationInfoNotBetween(String value1, String value2) {
            addCriterion("subway_station_info not between", value1, value2, "subwayStationInfo");
            return (Criteria) this;
        }

        public Criteria andIfTransferIsNull() {
            addCriterion("if_transfer is null");
            return (Criteria) this;
        }

        public Criteria andIfTransferIsNotNull() {
            addCriterion("if_transfer is not null");
            return (Criteria) this;
        }

        public Criteria andIfTransferEqualTo(String value) {
            addCriterion("if_transfer =", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferNotEqualTo(String value) {
            addCriterion("if_transfer <>", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferGreaterThan(String value) {
            addCriterion("if_transfer >", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferGreaterThanOrEqualTo(String value) {
            addCriterion("if_transfer >=", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferLessThan(String value) {
            addCriterion("if_transfer <", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferLessThanOrEqualTo(String value) {
            addCriterion("if_transfer <=", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferLike(String value) {
            addCriterion("if_transfer like", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferNotLike(String value) {
            addCriterion("if_transfer not like", value, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferIn(List<String> values) {
            addCriterion("if_transfer in", values, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferNotIn(List<String> values) {
            addCriterion("if_transfer not in", values, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferBetween(String value1, String value2) {
            addCriterion("if_transfer between", value1, value2, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andIfTransferNotBetween(String value1, String value2) {
            addCriterion("if_transfer not between", value1, value2, "ifTransfer");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdIsNull() {
            addCriterion("transfer_subway_id is null");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdIsNotNull() {
            addCriterion("transfer_subway_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdEqualTo(String value) {
            addCriterion("transfer_subway_id =", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdNotEqualTo(String value) {
            addCriterion("transfer_subway_id <>", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdGreaterThan(String value) {
            addCriterion("transfer_subway_id >", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_subway_id >=", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdLessThan(String value) {
            addCriterion("transfer_subway_id <", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdLessThanOrEqualTo(String value) {
            addCriterion("transfer_subway_id <=", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdLike(String value) {
            addCriterion("transfer_subway_id like", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdNotLike(String value) {
            addCriterion("transfer_subway_id not like", value, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdIn(List<String> values) {
            addCriterion("transfer_subway_id in", values, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdNotIn(List<String> values) {
            addCriterion("transfer_subway_id not in", values, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdBetween(String value1, String value2) {
            addCriterion("transfer_subway_id between", value1, value2, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayIdNotBetween(String value1, String value2) {
            addCriterion("transfer_subway_id not between", value1, value2, "transferSubwayId");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameIsNull() {
            addCriterion("transfer_subway_name is null");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameIsNotNull() {
            addCriterion("transfer_subway_name is not null");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameEqualTo(String value) {
            addCriterion("transfer_subway_name =", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameNotEqualTo(String value) {
            addCriterion("transfer_subway_name <>", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameGreaterThan(String value) {
            addCriterion("transfer_subway_name >", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameGreaterThanOrEqualTo(String value) {
            addCriterion("transfer_subway_name >=", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameLessThan(String value) {
            addCriterion("transfer_subway_name <", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameLessThanOrEqualTo(String value) {
            addCriterion("transfer_subway_name <=", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameLike(String value) {
            addCriterion("transfer_subway_name like", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameNotLike(String value) {
            addCriterion("transfer_subway_name not like", value, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameIn(List<String> values) {
            addCriterion("transfer_subway_name in", values, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameNotIn(List<String> values) {
            addCriterion("transfer_subway_name not in", values, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameBetween(String value1, String value2) {
            addCriterion("transfer_subway_name between", value1, value2, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andTransferSubwayNameNotBetween(String value1, String value2) {
            addCriterion("transfer_subway_name not between", value1, value2, "transferSubwayName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameIsNull() {
            addCriterion("district_name is null");
            return (Criteria) this;
        }

        public Criteria andDistrictNameIsNotNull() {
            addCriterion("district_name is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictNameEqualTo(String value) {
            addCriterion("district_name =", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotEqualTo(String value) {
            addCriterion("district_name <>", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameGreaterThan(String value) {
            addCriterion("district_name >", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameGreaterThanOrEqualTo(String value) {
            addCriterion("district_name >=", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameLessThan(String value) {
            addCriterion("district_name <", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameLessThanOrEqualTo(String value) {
            addCriterion("district_name <=", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameLike(String value) {
            addCriterion("district_name like", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotLike(String value) {
            addCriterion("district_name not like", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameIn(List<String> values) {
            addCriterion("district_name in", values, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotIn(List<String> values) {
            addCriterion("district_name not in", values, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameBetween(String value1, String value2) {
            addCriterion("district_name between", value1, value2, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotBetween(String value1, String value2) {
            addCriterion("district_name not between", value1, value2, "districtName");
            return (Criteria) this;
        }

        public Criteria andStartingTimeIsNull() {
            addCriterion("starting_time is null");
            return (Criteria) this;
        }

        public Criteria andStartingTimeIsNotNull() {
            addCriterion("starting_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartingTimeEqualTo(Date value) {
            addCriterion("starting_time =", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeNotEqualTo(Date value) {
            addCriterion("starting_time <>", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeGreaterThan(Date value) {
            addCriterion("starting_time >", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("starting_time >=", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeLessThan(Date value) {
            addCriterion("starting_time <", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeLessThanOrEqualTo(Date value) {
            addCriterion("starting_time <=", value, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeIn(List<Date> values) {
            addCriterion("starting_time in", values, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeNotIn(List<Date> values) {
            addCriterion("starting_time not in", values, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeBetween(Date value1, Date value2) {
            addCriterion("starting_time between", value1, value2, "startingTime");
            return (Criteria) this;
        }

        public Criteria andStartingTimeNotBetween(Date value1, Date value2) {
            addCriterion("starting_time not between", value1, value2, "startingTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andWeightsIsNull() {
            addCriterion("weights is null");
            return (Criteria) this;
        }

        public Criteria andWeightsIsNotNull() {
            addCriterion("weights is not null");
            return (Criteria) this;
        }

        public Criteria andWeightsEqualTo(String value) {
            addCriterion("weights =", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsNotEqualTo(String value) {
            addCriterion("weights <>", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsGreaterThan(String value) {
            addCriterion("weights >", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsGreaterThanOrEqualTo(String value) {
            addCriterion("weights >=", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsLessThan(String value) {
            addCriterion("weights <", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsLessThanOrEqualTo(String value) {
            addCriterion("weights <=", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsLike(String value) {
            addCriterion("weights like", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsNotLike(String value) {
            addCriterion("weights not like", value, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsIn(List<String> values) {
            addCriterion("weights in", values, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsNotIn(List<String> values) {
            addCriterion("weights not in", values, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsBetween(String value1, String value2) {
            addCriterion("weights between", value1, value2, "weights");
            return (Criteria) this;
        }

        public Criteria andWeightsNotBetween(String value1, String value2) {
            addCriterion("weights not between", value1, value2, "weights");
            return (Criteria) this;
        }
    }

    /**
     * subway_station_info
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * subway_station_info 2021-05-05
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}